version: '3.8'

services:
  db:
    image: postgres:15.0-alpine
    environment:
      POSTGRES_DB: DB_NAME
      POSTGRES_USER: USERNAME
      POSTGRES_PASSWORD: PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - my_volume:/home/orbis-service/Downloads/

volumes:
  my_volume:
  postgres_data:
