version: '3.8'

services:
  db:
    image: postgres:15.0-alpine
    environment:
      POSTGRES_DB: filedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: testadmin
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    image: working-with-files:1.0.0
    restart: "always"
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - /home/orbis-service/Downloads:/mnt
      - /home/orbis-service/Projects/orbis_test_flask/config_files/:/src/config_files

volumes:
  postgres_data:
