version: '3.8'

services:
  db:
    image: postgres:15.0-alpine
    environment:
      POSTGRES_DB: filedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: testadmin
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"  # Порт для AMQP
      - "15672:15672" # Порт для веб-интерфейса RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  fily-sync:
  image-processing:
    image: working-with-files:1.0.0
    restart: "always"
    ports:
      - "5000:5000"
    volumes:
      - /home/orbis-service/Projects/orbis_test_flask/config_files/:/src/config_files

  image-processing-worker:
    image: working-with-files:1.0.0
    restart: "always"
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - /home/orbis-service/Projects/orbis_test_flask/config_files/:/src/config_files

volumes:
  postgres_data:
