version: '3.8'

services:
  db:
    image: postgres:15.0-alpine
    environment:
      POSTGRES_DB: filedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: testadmin
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  file-sync:
    image: file-sync:1.0.0
    restart: "always"
    ports:
      - "5000:5000"
    volumes:
      - /home/orbis-service/Projects/orbis_test_flask/config_files/:/src/config_files

volumes:
  postgres_data:
